config/routes.rb
Rails.application.routes.draw do

  root "houses#index"
  
  resources :appliances
  resources :projects
  resources :contacts
  resources :houses
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appliance.rb
# == Schema Information
#
# Table name: appliances
#
#  id             :bigint           not null, primary key
#  appliance_type :string
#  category       :string
#  last_serviced  :date
#  make           :string
#  model          :string
#  notes          :text
#  service_due    :date
#  year           :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  contact_id     :bigint
#  house_id       :bigint           not null
#
# Indexes
#
#  index_appliances_on_contact_id  (contact_id)
#  index_appliances_on_house_id    (house_id)
#
# Foreign Keys
#
#  fk_rails_...  (contact_id => contacts.id)
#  fk_rails_...  (house_id => houses.id)
#
class Appliance < ApplicationRecord
  belongs_to :house
  belongs_to :contact, required: false
  has_one :owner, through: :house, source: :owner
end

app/controllers/appliances_controller.rb
class AppliancesController < ApplicationController
  before_action :set_appliance, only: %i[ show edit update destroy ]

  
                                
  # GET /appliances or /appliances.json
  def index
    @appliances = current_user.appliances
  end

  # GET /appliances/1 or /appliances/1.json
  def show
  end

  # GET /appliances/new
  def new
    @appliance = Appliance.new
    @possible_appliance_types = ["Air Conditioner","Water Heater","Sump Pump","Furnace","Range","Oven",
                                "Stove","Microwave","Dishwasher","Washing Machine","Dryer","Other"]
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /appliances/1/edit
  def edit
    @possible_appliance_types = ["Air Conditioner","Water Heater","Sump Pump","Furnace","Range","Oven",
                                "Stove","Microwave","Dishwasher","Washing Machine","Dryer","Other"]
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /appliances or /appliances.json
  def create
    @appliance = Appliance.new(appliance_params)
    @appliance.house_id = current_user.houses.first.id
    @appliance.service_due = @appliance.last_serviced + 1.years

    respond_to do |format|
      if @appliance.save
        format.html { redirect_to appliance_url(@appliance), notice: "Appliance was successfully created." }
        format.json { render :show, status: :created, location: @appliance }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appliances/1 or /appliances/1.json
  def update
    respond_to do |format|
      if @appliance.update(appliance_params)
        format.html { redirect_to appliance_url(@appliance), notice: "Appliance was successfully updated." }
        format.json { render :show, status: :ok, location: @appliance }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appliances/1 or /appliances/1.json
  def destroy
    @appliance.destroy

    respond_to do |format|
      format.html { redirect_to appliances_url, notice: "Appliance was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appliance
      @appliance = Appliance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appliance_params
      params.require(:appliance).permit(:category, :appliance_type, :make, :model, :year, :last_serviced, :service_due, :notes, :house_id, :contact_id)
    end
end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/views/appliances/_all_appliances.html.erb
<div class="row mb-4" id="all_appliances">
  <div class="col-md-4" id="new_appliance_card">
    <div class="card" style="width: 18em;" id="new_appliance_button">
      <%= link_to new_appliance_path, class: "card-image-top", remote: true do %>
        <h5>Add New Appliance</h5>
        <img src="https://media.istockphoto.com/vectors/black-plus-sign-positive-symbol-vector-id688550958?k=20&m=688550958&s=612x612&w=0&h=wvzUqT3u3feYygOXg3GB9pYBbqIsyu_xpvfTX-6HOd0=" class="card-img-bottom">
      <% end %>
    </div>
  </div>
  <% appliances.each do |appliance| %>
    <div class="col-md-4">
      <%= render "appliances/appliance", appliance: appliance %>
    </div>
  <% end %>
</div>

app/views/appliances/_appliance.html.erb
<div id="<%= dom_id(appliance) %>" class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= appliance.appliance_type %></h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Make: <%= appliance.make %></li>
    <li class="list-group-item">Model: <%= appliance.model %></li>
    <li class="list-group-item">Last Serviced: <%= appliance.last_serviced %></li>
    <li class="list-group-item">Service Due: <%= appliance.service_due %></li>
    <% if appliance.contact_id.present? %>
      <li class="list-group-item">Contact: <%= appliance.contact.contact_name %></li>
    <% end %>
  </ul>
  <div class="card-body">
    <%= link_to "Edit", edit_appliance_path(appliance.id), class: "card-link", remote: true %>
    <%= link_to 'Delete', appliance, method: :delete, class: "card-link", remote: true %>
  </div>
</div>

app/views/appliances/_form.html.erb
<div id="<%= dom_id(appliance) %>_form">
  <%= form_with(model: appliance, local: false) do |form| %>
    <% if appliance.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(appliance.errors.count, "error") %> prohibited this appliance from being saved:</h2>

        <ul>
          <% appliance.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :category %>
      <%= form.select :category, ['Mechanical','Kitchen','Laundry','Other'], :prompt => 'Select One' %>
    </div>

    <div class="field">
      <%= form.label :appliance_type %>
      <%= form.select :appliance_type, @possible_appliance_types.map {|value| [value,value]}, :prompt => 'Select One' %>
    </div>

    <div class="field">
      <%= form.label :make %>
      <%= form.text_field :make %>
    </div>

    <div class="field">
      <%= form.label :model %>
      <%= form.text_field :model %>
    </div>

    <div class="field">
      <%= form.label :year %>
      <%= form.number_field :year %>
    </div>

    <div class="field">
      <%= form.label :last_serviced %>
      <%= form.date_select :last_serviced %>
    </div>

    <div class="field">
      <%= form.label :notes %>
      <%= form.text_area :notes %>
    </div>

    <div class="field">
      <%= form.label :contact_id %>
      <%= form.select :contact_id, current_user.contacts.collect {|c| [c.contact_name, c.id] }, include_blank: true %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/appliances/create.js.erb
$("#all_appliances").replaceWith("<%= j(render 'appliances/all_appliances') %>");

app/views/appliances/destroy.js.erb
$("#<%= dom_id(@appliance) %>").fadeOut(function() {
  $(this).remove();
});

app/views/appliances/edit.html.erb
<h1>Editing Appliance</h1>

<%= render 'form', appliance: @appliance %>

<%= link_to 'Show', @appliance %> |
<%= link_to 'Back', appliances_path %>

app/views/appliances/edit.js.erb
$("#<%= dom_id(@appliance) %>").replaceWith("<%= j(render "appliances/form", appliance: @appliance) %>");

app/views/appliances/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row mb-4">
  <h1>Appliances</h1>
</div> 

<%= render "appliances/all_appliances", appliances: @appliances %>

app/views/appliances/new.html.erb
<h1>New Appliance</h1>

<%= render 'form', appliance: @appliance %>

<%= link_to 'Back', appliances_path %>

app/views/appliances/new.js.erb
$("#new_appliance_button").replaceWith("<%= j(render "appliances/form", appliance: @appliance) %>");

app/views/appliances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @appliance.category %>
</p>

<p>
  <strong>Type:</strong>
  <%= @appliance.appliance_type %>
</p>

<p>
  <strong>Make:</strong>
  <%= @appliance.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @appliance.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @appliance.year %>
</p>

<p>
  <strong>Last serviced:</strong>
  <%= @appliance.last_serviced %>
</p>

<p>
  <strong>Service due:</strong>
  <%= @appliance.service_due %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appliance.notes %>
</p>

<p>
  <strong>House:</strong>
  <%= @appliance.house_id %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @appliance.contact_id %>
</p>

<%= link_to 'Edit', edit_appliance_path(@appliance) %> |
<%= link_to 'Back', appliances_path %>

app/views/appliances/update.js.erb
$("#<%= dom_id(@appliance) %>_form").replaceWith("<%= j(render @appliance) %>");