config/routes.rb
Rails.application.routes.draw do

  root "houses#index"
  
  resources :appliances
  resources :projects
  resources :contacts
  resources :houses
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]

  # GET /houses or /houses.json
  def index
    @houses = current_user.houses
  end

  # GET /houses/1 or /houses/1.json
  def show
    authorize @house
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)
    @house.owner = current_user

    respond_to do |format|
      if @house.save
        format.html { redirect_to house_url(@house), notice: "House was successfully created." }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to house_url(@house), notice: "House was successfully updated." }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url, notice: "House was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.require(:house).permit(:street_address, :city, :state, :zip_code, :purchase_date, :owner_id)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :purchase_date %>
    <%= form.date_select :purchase_date %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Purchase date</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.street_address %></td>
        <td><%= house.city %></td>
        <td><%= house.state %></td>
        <td><%= house.zip_code %></td>
        <td><%= house.purchase_date %></td>
        <td><%= house.owner_id %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street address:</strong>
  <%= @house.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @house.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @house.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @house.zip_code %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @house.purchase_date %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @house.owner_id %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>